export const sampleFinancialProfile = {
  age: 35,
  state: "NY",
  gross_annual_income: "85000.00",
  monthly_take_home_income: "5200.00",
  income_pattern: "mostly_stable",
  monthly_housing_cost: "1800.00",
  monthly_non_housing_essential_expenses: "900.00",
  monthly_discretionary_expenses: "400.00",
  assets: {
    cash: "12000.00",
    retirement: "45000.00",
    brokerage: "8000.00",
    other: "3000.00",
  },
  debts: [
    {
      name: "Student loan",
      debt_type: "student_loan",
      balance: "18000.00",
      annual_interest_rate: "5.25",
      monthly_payment: "250.00",
      interest_tax_advantaged: true,
    },
    {
      name: "Auto loan",
      debt_type: "auto_loan",
      balance: "15000.00",
      annual_interest_rate: "6.75",
      monthly_payment: "420.00",
      interest_tax_advantaged: false,
    },
    {
      name: "Credit card",
      debt_type: "credit_card",
      balance: "2000.00",
      annual_interest_rate: "22.90",
      monthly_payment: "100.00",
      interest_tax_advantaged: false,
    },
  ],
  monthly_investment_contribution: "500.00",
  contribution_breakdown: {
    traditional_401k: "300.00",
    roth_401k: "100.00",
    payroll_hsa: "50.00",
    direct_hsa: "0.00",
    taxable_brokerage: "50.00",
    other: "0.00",
  },
  investment_projection_assumptions: {
    years: 10,
    annual_return_rate: "7.00",
    annual_inflation_rate: "2.50",
  },
  financial_goals: ["Build emergency fund", "Retire at 65"],
  risk_tolerance: "medium",
  job_stability: "high",
  expected_years_in_current_location: 4,
  dependents: 0,
  variable_income_context: {
    income_types: ["bonus_commission_or_overtime"],
    included_in_monthly_take_home_income: false,
  },
  expected_job_or_income_change: null,
  has_delinquent_debt: false,
  monthly_employer_retirement_match_contribution: "200.00",
  relevant_insurance_coverage: ["health", "auto"],
  known_major_upcoming_expenses: [],
  active_life_event: null,
} as const;
